suse-edge/upgrade-controller

- config/rbac/role.yaml
- internal/controller/reconcile_os.go
- internal/controller/upgradeplan_controller.go
- internal/upgrade/os.go
- internal/upgrade/templates/os-upgrade.sh.tpl
- manifests/release-3.0.1.yaml
- pkg/release/release.go
Initial implementation of the script that will do the actual OS upgrade or migration.
Script has the following functionalities:
1. Determine whether it should do an OS package upgrade of OS migration - This is done by looking at the IBS Common Platform Enumeration (CPE) for the currently running OS and comparing it with the one in the release manifest. If they are the same this indicates that the OS version is the same as the one in the release manifest and a package upgrade should be performed. If there is a CPE mismatch, then this indicates a different OS version => migration is performed instead.
2. Dynamically determine the OS architecture on which it is running and based on it use the correct `name/version/arch` naming for the `--product` provided for migration. Also validates …
> Initial implementation and integration of the OS upgrade script

- api/v1alpha1/upgradeplan_types.go
- config/rbac/role.yaml
- internal/controller/reconcile_os.go
- internal/controller/upgradeplan_controller.go
- internal/upgrade/base.go
- internal/upgrade/kubernetes.go
- internal/upgrade/os.go
- internal/upgrade/templates/os-upgrade.sh.tpl
- manifests/release-3.0.1.yaml
- pkg/release/release.go
Introduces OS upgrades for clusters consisting of one node. Multi-node cluster OS upgrade will be handled in a different PR.
Tested for:
* 5.5 OS package upgrade + K8s upgrade
* 5.5 -> 6.0 OS migration + K8s upgrade
Migration screenshots:
Before:
After:
**os-upgrade.sh.tpl** has been refactored and now supports the following functionalities:
* Validation for the exit code of the systemd upgrade service. Currently with `transactional-update run` the exit codes are not propagated well, but when we move to `transactional-update migration` this functionality will be useful
* In light of the fact that we use SUC and when an OS reboots the SUC job will restart the pod, a validation was added to the script that ensures that `transactional-update` will not be called again once the OS reboots
* To …
> OS upgrade implementation for single clusters

- internal/controller/reconcile_kubernetes.go
- internal/controller/reconcile_os.go
Now that we do not reconcile when an SUC Plan is created, we need to ad the "InProgress" condition during the SUC Plan creation.
We also update the timestamps for the "InProgress" condition when we do a validation of the specific component upgrade.
> Add "InProgress" condition both on Plan creation and upgrade validation steps

- internal/controller/reconcile_os.go
- internal/controller/upgradeplan_controller.go
- internal/upgrade/os.go
Introduces implementation for handling OS upgrades over clusters consisting of multiple nodes.
Tested for:
1. 5.5 OS package upgrade 
2. 5.5 -> 6.0 OS migration + K8s upgrade + Rancher upgrade 
Benchmarks:
- For (1) ~ 30 minutes for all packages of all nodes to be upgraded
- For (2) ~ a little over an hour for everything
Migration screenshots:
Before:
After:
UpgradePlan Conditions:
Note:
- **Node drain** logic is not part of this PR, it will come next as it requires more testing
Known **non-blocking** issues:
Currently the 5.5 -> 6.0 migration produces the following error once all packages have been installed:
>Can't determine the list of installed products after migration: Get "https://scc.suse.com/connect/systems/activations": dial tcp: lookup scc.suse.com on [::1]:53: read udp …
> OS upgrade implementation for multi node clusters

- api/v1alpha1/upgradeplan_types.go
- internal/controller/reconcile_longhorn.go
- internal/controller/upgradeplan_controller.go
- manifests/release-3.0.1.yaml
- pkg/release/release.go
- Adds Longhorn reconciler following similar upgrade flow to Rancher
- Follow up will address condition check for whether the installed chart version is the same as the one in the release manifest
> Upgrade Longhorn

- internal/controller/helm.go
- internal/controller/reconcile_longhorn.go
- internal/controller/reconcile_rancher.go
- internal/controller/upgradeplan_controller.go
- internal/upgrade/base.go
- Chart versions may not change between different releases
- Introduce an annotation to the `HelmChart` resource in order to differentiate whether an upgrade was just triggered or if it should be skipped
> Skip chart version upgrades between identical releases

- api/v1alpha1/upgradeplan_types.go
- config/crd/bases/lifecycle.suse.com_upgradeplans.yaml
- internal/controller/reconcile_kubernetes.go
- internal/controller/reconcile_os.go
- internal/controller/upgradeplan_controller.go
- internal/upgrade/base.go
- internal/upgrade/kubernetes.go
- internal/upgrade/os.go
As discussed previously the upgrade-controller should:
1. Drain the control-plane and worker nodes for both K8s and OS upgrades
2. Offer the possibility to disable node drain for control-plane/worker nodes or disable the whole node drain procedure of the upgrade-controller
By default the upgrade-controller will execute drain with the following flags:
- `--delete-emptydir-data` - continue drain even if there are pods utilising `emptyDir` storage
-  `--timeout 15m0s` - the amount of time for which to wait for the drain operation to finish. Ensures that the drain operation will not block the upgrade flow
- `--ignore-daemonsets` - ignores DaemonSet-managed pods
- `--force` - continue even if there are pods that do not have a controller (single pods)
Due to the nature of how we do upgrades, …
> Add drain logic for upgrade-controller SUC plans

- api/v1alpha1/upgradeplan_types.go
- internal/controller/helm.go
- internal/controller/reconcile_longhorn.go
- internal/controller/reconcile_rancher.go
- internal/controller/upgradeplan_controller.go
- internal/upgrade/helm.go
- First attempt towards unified Helm chart upgrades
> Unify Helm chart upgrades

- api/v1alpha1/upgradeplan_types.go
- internal/controller/helm.go
- internal/controller/reconcile_metallb.go
- internal/controller/upgradeplan_controller.go
- manifests/release-3.0.1.yaml
- pkg/release/release.go
Introduces upgrades for the `MetalLB` helm chart.
**_Notes:_**
Due to the fact that MetalLB is the first SUSE Edge team supported helm chart that is being included in the `upgrade-controller` some changes needed to be made to the existing chart upgrade implementation. Changes include:
1. A new property was added to the `Release Manifest` called `releaseName`. Its idea is to represent the name of the Helm release that we need to search for. This was needed, mainly because for OCI-based Helm charts we need to provide the full chart URL under the `<component>.chart` property. We previously used this property to find the release related to the specific chart. The suggested logic checks whether `releaseName` exists, if it exists this is the property that is used in the `retrieveHelmRelease()` …
> Upgrade MetalLB

- manifests/release-3.0.1.yaml
- pkg/release/release.go
The `namespace` property from the release manifest is no longer used by the controller, so we can remove it.
> Remove unused namespace property

- api/v1alpha1/upgradeplan_types.go
- internal/controller/reconcile_kubevirt.go
- internal/controller/upgradeplan_controller.go
- manifests/release-3.0.1.yaml
- pkg/release/release.go
Kubevirt chart upgrade implementation.
Note:
- In order to prevent unwanted errors, the `0.2.4` version is used in the release manifest, because `0.3.0` is not yet present in `registry.suse.com/edge/kubevirt-chart`.
> Kubevirt chart upgrade

- api/v1alpha1/upgradeplan_types.go
- internal/controller/helm.go
- internal/controller/reconcile_neuvector.go
- internal/controller/upgradeplan_controller.go
- internal/upgrade/helm.go
- manifests/release-3.0.1.yaml
- pkg/release/release.go
- Introduces NeuVector component upgrade
- NeuVector is a component consisting of two different Helm charts (CRDs being extracted in a separate one)
- The upgrade procedure relies on upgrading the CRD chart first and then proceeding with the main one
- Discrepancies between the charts is handled where we:
- Consider the upgrade failed if the CRD is upgraded but the main chart does not exist
- Allow for main chart upgrades even if the CRD version is already installed on the cluster
> Upgrade NeuVector

- internal/controller/reconcile_cdi.go
- internal/controller/reconcile_kubevirt.go
- internal/controller/reconcile_longhorn.go
- internal/controller/reconcile_metallb.go
- internal/controller/reconcile_rancher.go
- internal/upgrade/helm.go
Drop the `Message()` helm state function in favour of the more informative `FormattedMessage()` function.
> Drop message func in favour of using formatted message

- internal/controller/reconcile_kubevirt.go
- internal/controller/upgradeplan_controller.go
- manifests/release-3.0.1.yaml
- pkg/release/release.go
Kubevirt dashboard upgrade implementation.
Upgrade is done as part of the Kubevirt upgrade, where:
- If Kubevirt is missing, the dashboard is not upgraded
- If Kubevirt upgrade fails, the dashboard is not upgraded
In order to not produce misleading conditions, the following flow is followed:
- If dashboard upgrade fails we count the KubeVirt upgrade as succeeded and we add a warning event to the UpgradePlan - reasoning here is mainly that KubeVirt is the main upgrade component and the condition is counted as succeeded when KubeVirt is upgraded. Add-on component failures are added as warnings.
- If the dashboard upgrade is missing, or it is not eligible for upgrade (the chart is with the same version as the one specified in the release manifest), then the condition for the KubeVirt chart …
> Kubevirt dashboard upgrade

- internal/controller/reconcile_akri.go
- manifests/release-3.0.1.yaml
- pkg/release/release.go
Screenshot of a successfully upgraded Akri chart, but failed add-on dashboard chart:
Screenshot of a successful Akri and dashboard upgrade:
Screenshot of a successful Akri upgrade when dashboard is missing:
Screenshot when Akri is missing, but dashboard is there/missing (it is the same output):
> Akri dashboard upgrade

- config/rbac/role.yaml
- internal/controller/upgradeplan_controller.go
- Ensures both Helm controller and SUC are present on start up
- If either of these are disabled or uninstalled at runtime, then the Upgrade controller will also be unable to work
- In the future we might want to implement a CRD watching logic in a separate lightweight controller instance which would notify the main one for changes but this is currently out of scope
> Verify installation of dependency controllers

- cmd/main.go
- config/manager/manager.yaml
- config/samples/lifecycle_v1alpha1_releasemanifest.yaml
- config/samples/lifecycle_v1alpha1_upgradeplan.yaml
- internal/controller/helm.go
- internal/controller/reconcile_helm.go
- internal/controller/reconcile_kubernetes.go
- internal/controller/reconcile_os.go
- internal/controller/upgradeplan_controller.go
- internal/upgrade/base.go
- internal/upgrade/helm.go
- internal/upgrade/kubernetes.go
- internal/upgrade/os.go
- Introduces a CLI arg (also configurable via env variable) to set watch namespace
- The controller would only monitor for resources in said namespace if provided, or watch the whole cluster if not
- Drops controller references as those are no longer possible across different namespaces (i.e. an `UpgradePlan` created in the `upgrade-controller-system` namespace cannot be a parent of a `Secret` in the `cattle-system` namespace)
- Makes use of annotations to handle the connection between resources
- Records creation events of `HelmChart` resources
- **Does not** modify RBAC using kubebuilder since that would require a hardcoded namespace
-  This will be revisited once we start working on a Helm chart
> Specify watch namespace

- internal/controller/reconcile_kubernetes.go
- internal/controller/reconcile_os.go
- internal/upgrade/templates/os-upgrade.sh.tpl
As per the [official](https://documentation.suse.com/sle-micro/6.0/html/Micro-upgrade/index.html#upgrading-micro-preparation-patching) SLE Micro upgrade docs the users need to ensure that packages are updated before doing a version migration.
Sadly doing just `transactional-update patch` over an older image is not enough for a successful migration. 
In order to not force users to have to do an additional manual command, this PR introduces an enhancement over the existing OS migration logic, where before migrating we do an automatic update of all OS packages, ensuring that the operation will succeed.
The PR introduces the following code changes:
1. The indentations of the `os-upgrade.sh` template have been changed in order to make the `heredoc` more readable
2. Logic has been introduced to …
> Do OS package upgrades before doing migration

- api/v1alpha1/releasemanifest_types.go
- api/v1alpha1/zz_generated.deepcopy.go
- config/crd/bases/lifecycle.suse.com_releasemanifests.yaml
- internal/controller/reconcile_os.go
- internal/upgrade/os.go
- internal/upgrade/templates/os-upgrade.sh.tpl
The suggested implementation introduces the following changes:
1. Removal of the existing OS arch validation that was located in the `os-upgrade.sh.tpl` script template
2. Rework of the `SupportedArchs` property of the `OperatingSystem` release manifest configuration:
- The property has been moved away from a `[]string` to a `[]Arch` type
- Validation was added for each `Arch` entry that it holds expected full arch names - `x86_64` and `aarch64` have been added as initial possible configurations.
- Logic that converts arch full names to short names (e.g. `amd64`, `arm64`.. etc.) was added.
3. OS arch validation is now done by the `upgrade-controller`, where:
- each cluster node is validated against the supported architectures (both full name and short name) that have been defined in the …
> Move arch validation logic outside of OS upgrade script

- internal/upgrade/kubernetes.go
SUC through the following warning for K8s SUC Plans:
```bash
W0823 13:20:39.497039       1 warnings.go:70] metadata.name: this is used in Pod names and hostnames, which can result in surprising behavior; a DNS label is recommended: [must not contain dots]
```
This was caused, because K8s SUC Plans had dots in their names => SUC created Pod with dots in their name.
This PR suggest a fix for this problem, where we replace "." with "-".
SUC Plan naming before:
```bash
cp1rke2:~/upgrade-controller # k get plans
NAME                           IMAGE                                 CHANNEL   VERSION
control-plane-v1.28.9-rke2r1   rancher/rke2-upgrade                            v1.28.9+rke2r1
workers-v1.28.9-rke2r1         rancher/rke2-upgrade                            v1.28.9+rke2r1
```
SUC …
> Replace dots with "-" in K8s SUC Plan naming

- api/v1alpha1/releasemanifest_types.go
- api/v1alpha1/upgradeplan_types.go
- config/crd/bases/lifecycle.suse.com_releasemanifests.yaml
- config/crd/bases/lifecycle.suse.com_upgradeplans.yaml
- go.mod
- internal/controller/helm.go
- internal/controller/helm_test.go
- Adds support for additional Helm values in the ReleaseManifest custom resource
- Adds support for additional Helm values in the UpgradePlan custom resource
- User supplied values (via UpgradePlan spec) have higher priority than platform supplied values (via ReleaseManifest spec)
> Allow custom helm values

- internal/controller/release_manifest.go
- internal/upgrade/base_test.go
- internal/upgrade/helm_test.go
- internal/upgrade/kubernetes_test.go
- internal/upgrade/os_test.go
- internal/upgrade/release_manifest.go
- internal/upgrade/release_manifest_test.go
- Adds unit tests covering the construction of different resources in the upgrade package
- Tests do include a lot of repetition and manual assertions due to the nature of the constantly changing resources
> Add tests for internal/upgrade package

- cmd/main.go
- config/manager/manager.yaml
- config/samples/lifecycle_v1alpha1_releasemanifest.yaml
- config/samples/lifecycle_v1alpha1_upgradeplan.yaml
- internal/controller/release_manifest.go
- internal/controller/upgradeplan_controller.go
- internal/upgrade/release_manifest.go
- internal/upgrade/release_manifest_test.go
- Introduces an init container to copy the ReleaseManifest custom resources
- Adjusts the main container to apply the ReleaseManifest from the init copy
> Split release manifest applying

- internal/upgrade/os.go
- Bump `bci-base` version to correct Edge 3.1 version
- Increase OS upgrade Job timeout to ensure that Jobs will not be deleted before they run
> Minor refactor

- go.mod
- internal/controller/helm.go
- internal/controller/helm_test.go
- Moves to YAML unmarshaling from Helm chart values coming from HelmChart resource
- Keeps JSON unmarshaling from ReleaseManifest resource due to the `apiextensionsv1.JSON` values
> Use yaml package for (un)marshaling custom values

- api/v1alpha1/releasemanifest_types.go
- api/v1alpha1/upgradeplan_types.go
- internal/controller/reconcile_kubernetes.go
- internal/controller/reconcile_os.go
- internal/controller/reconcile_os_test.go
- internal/controller/upgradeplan_controller.go
- Executes node architecture validation first in order not to block executing upgrades
- Moves supported architectures definition to the v1alpha1 package
- Introduces a ValidationFailed condition
> Reorder node validation

- .github/workflows/build_and_test.yml
- api/v1alpha1/releasemanfest_types_test.go
- api/v1alpha1/upgradeplan_webhook.go
- api/v1alpha1/upgradeplan_webhook_test.go
- Ensures both creating and updating plans with empty release version will fail
- Reorder some of the update validations in order of priority
- Add webhook tests ensuring the proper workflow of upgrade plan validation
> Add webhook tests

- cmd/main.go
- The build tag for the release manifest container image now no longer uses the `suse/` prefix
- This is the only incorrect occurrence in the codebase
> Fix release manifest image path

- internal/upgrade/kubernetes.go
- internal/upgrade/kubernetes_test.go
We've identified that we run into some issues when upgrading the Kubernetes versions on worker nodes. In the future, we'd like to revisit this and enable _faster_ upgrades, however, going for a non-concurrent approach for these upgrades seem to be the safer option in the short term.
> Use a non-concurrent approach to Kubernetes worker upgrades

- api/v1alpha1/releasemanifest_types.go
- config/crd/bases/lifecycle.suse.com_releasemanifests.yaml
- config/samples/lifecycle_v1alpha1_releasemanifest.yaml
- helm/upgrade-controller/charts/lifecycle-crds/templates/release-manifest-crd.yaml
- internal/upgrade/os.go
- internal/upgrade/os_test.go
- internal/upgrade/templates/os-upgrade.sh.tpl
closes: #93 
With the new `suseconnect-ng` version, we can now utilise the `--gpg-auto-import-keys` flag of the `zypper migration` command.
This means that:
1. We no longer need the `gpgRepoPath` property, as with `--gpg-auto-import-keys` flag we automatically import the key
2. Third-party repositories are added automatically as well which closes #93.
Examples with new functionality, where the node has the following third-party repositories:
```bash
zypper ar https://download.opensuse.org/repositories/SUSE:/CA/SLE_15_SP5 opensuse-ca
zypper ar https://download.nvidia.com/suse/sle15sp5/ nvidia
```
Automatically imported repo keys for the 6.0 SL Micro repo + `nvidia` and `opensuse-ca`:
```bash
Retrieving repository 'SL-Micro-6.0-Pool' metadata [......
Automatically importing the following …
```
> Fix OS migration bug

- internal/controller/reconcile_kubernetes.go
- internal/controller/reconcile_kubernetes_test.go
- internal/controller/reconcile_os.go
- internal/controller/reconcile_os_test.go
Closes https://github.com/suse-edge/upgrade-controller/issues/76
> Improve node matching

- internal/controller/helm.go
- internal/controller/reconcile_kubernetes.go
- internal/controller/reconcile_os.go
- internal/controller/release_manifest.go
- internal/controller/upgradeplan_controller.go
- internal/upgrade/base.go
- internal/upgrade/base_test.go
- internal/upgrade/kubernetes.go
- internal/upgrade/kubernetes_test.go
- internal/upgrade/os.go
- internal/upgrade/os_test.go
- internal/upgrade/release_manifest.go
- internal/upgrade/release_manifest_test.go
Moving away from using annotations in favour of labels will give us and the users a bit more flexibility when working with the resources created by the `upgrade-controller`.
If we use labels users would be able to differentiate between which resource is for which plan, by simply doing something similar to this:
```bash
NAME                                      IMAGE                                 CHANNEL   VERSION
control-plane-sl-micro-6-0-d5e64109df     registry.suse.com/bci/bci-base:15.6             3.1.0
control-plane-v1-30-3-rke2r1-d5e64109df   rancher/rke2-upgrade                            v1.30.3+rke2r1
workers-sl-micro-6-0-d5e64109df           registry.suse.com/bci/bci-base:15.6             3.1.0
workers-v1-30-3-rke2r1-d5e64109df         rancher/rke2-upgrade …
```
> Move away from using annotations in favour of labels
